### ISSUE TITLE
Null Pointer Exception in Translator

### ISSUE THREAD

**Issue by lonely-lockley** [lonely-lockley/archinsight#89]
New Mirroring feature causes an NPE in some cases. I can see this in logs:
```
24.08.2024 11:58:19.537 ERROR [virtual-executor581] i.m.http.server.RouteExecutor - Unexpected error occurred: Cannot invoke "com.github.lonelylockley.archinsight.parse.WithSource.getCharPosition()" because the return value of "com.github.lonelylockley.archinsight.model.imports.AbstractImport.getElementSource()" is null
java.lang.NullPointerException: Cannot invoke "com.github.lonelylockley.archinsight.parse.WithSource.getCharPosition()" because the return value of "com.github.lonelylockley.archinsight.model.imports.AbstractImport.getElementSource()" is null
at com.github.lonelylockley.archinsight.link.Linker.lambda$rewriteImportsInternal$4(Linker.java:103)
at com.github.lonelylockley.archinsight.model.Functional$2.foreach(Functional.java:47)
at com.github.lonelylockley.archinsight.link.Linker.rewriteImportsInternal(Linker.java:99)
at com.github.lonelylockley.archinsight.link.Linker.rewriteImports(Linker.java:123)
at com.github.lonelylockley.archinsight.link.Linker.checkIntegrity(Linker.java:255)
at com.github.lonelylockley.archinsight.TranslatorService.translate(TranslatorService.java:70)
at com.github.lonelylockley.archinsight.$TranslatorService$Definition$Intercepted.$$access$$translate(Unknown Source)
at com.github.lonelylockley.archinsight.$TranslatorService$Definition$Exec.dispatch(Unknown Source)
at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:442)
at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
at com.github.lonelylockley.archinsight.tracing.ResponseTimeMeasuringInterceptor.intercept(ResponseTimeMeasuringInterceptor.java:26)
at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
at com.github.lonelylockley.archinsight.$TranslatorService$Definition$Intercepted.translate(Unknown Source)
at com.github.lonelylockley.archinsight.$TranslatorService$Definition$Exec.dispatch(Unknown Source)
at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:447)
at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4214)
at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:263)
at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:74)
at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:480)
at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:457)
at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```

Don't know how to reproduce yet

**Comment by lonely-lockley** [comment]
The problem was in using import statement without element type declaration. If it's null, identifier source positions should be used
